# -*- coding: utf-8 -*-
"""Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cuwf2NWsO74UPHea0YnmgqNN3gtqwnpx
"""

import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

data = pd.read_csv('/content/House Price Prediction.csv')

data.head()

data.info()

data.describe()

data.isnull().sum()

X = data.drop('Price(USD)', axis = 1)
y = data['Price(USD)']

X.columns

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

model = LinearRegression()
model = model.fit(X_train,y_train)

y_predic = model.predict(X_test)

print("Mean Sequared Error : ", mean_squared_error(y_test,y_predic))

plt.scatter(y_test,y_predic,color='blue',alpha=0.6,edgecolors='k')
plt.plot([y_test.min(),y_predic.max()],[y_test.min(),y_predic.max()],'r--',lw=4)
plt.xlabel('Actual Price')
plt.ylabel('Predicted Price')
plt.title('Actual Price vs Predicted Price')
plt.show()